### ISSUE TITLE
[BUG] log files stopped recording 

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/NeonCore#689] opened 2024-06-09 13:54 UTC
### Description

DEBUG was turned on

possibly a 10MB limit on log file's combined memory usage 
only had 1 hour 14 minutes of logging 
as log file were no longer updated for over 12 hours

### Steps to Reproduce

in the morning set
log_level=DEBUG in ~/.config/neon/neon.yaml
gui-menu-pulldown > select Reboot Services
.. did some voice commands
.. did 'top' commands from time to time, collected the log files to my host machine
had some issues with latency in the evening 
checked logs - bam! cut off [skills.log was cut-off in mid text !!]

### Other Notes

```
started bus.log
2024-06-08 03:58:55.640 - bus - neon_messagebus.service.__main__:main:51 - DEBUG - Waiting for exit signal
2024-06-08 03:58:55.645 - bus - neon_messagebus.service:run:105 - INFO - Starting message bus service...
2024-06-08 03:58:55.648 - bus - ovos_messagebus.load_config:load_message_bus_config:33 - INFO - Loading message bus configs
2024-06-08 03:58:55.654 - bus - neon_messagebus.service:_listen:176 - INFO - Starting Messagebus server with config: MessageBusConfig(host='0.0.0.0', port=8181, route='/core', ssl=None)
2024-06-08 03:58:55.658 - bus - neon_messagebus.service:_listen:192 - INFO - ws listener started
2024-06-08 03:58:55.666 - bus - ovos_bus_client.conf:load_message_bus_config:28 - DEBUG - Loading message bus configs
2024-06-08 03:58:55.723 - bus - ovos_bus_client.client.client:on_open:93 - DEBUG - Connected
2024-06-08 03:58:55.734 - bus - neon_messagebus.service:_init_signal_manager:144 - INFO - Signal Manager started
2024-06-08 03:58:55.838 - bus - ovos_messagebus.event_handler:on_message:51 - DEBUG - ovos.session.sync source: [] destination: []
SESSION: {'active_skills': [], 'utterance_states': {}, 'session_id': 'default', 'lang': 'en-us', 'context': {'timeout': 120, 'frame_stack': []}, 'site_id': 'unknown', 'pipeline': ['stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'padatious_medium', 'adapt_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low'], 'location': {'city': {'code': 'Greenville', 'name': 'Greenville', 'state': {'code': 'SC', 'name': 'South Carolina', 'country': {'code': 'US', 'name': 'United States'}}}, 'coordinate': {'latitude': 34.8308, 'longitude': -82.3507}, 'timezone': {'code': 'America/New_York', 'name': 'America/New_York', 'dstOffset': 3600000, 'offset': -28800000}}, 'system_unit': 'imperial', 'time_format': 'half', 'date_format': 'MDY', 'is_speaking': False, 'is_recording': False, 'blacklisted_skills': ['skill-ovos-setup.openvoiceos', 'skill-messaging.neongeckocom', 'skill-custom_conversation.neongeckocom', 'skill-instructions.neongeckocom', 'skill-audio_record.neongeckocom'], 'blacklisted_intents': []}
2024-06-08 03:58:56.174 - bus - neon_messagebus.util.mq_connector:start_mq_connector:42 - INFO - Skipping MQ Connector init
2024-06-08 03:58:56.178 - bus - neon_messagebus.service:_init_mq_connector:157 - INFO - No MQ Credentials provided
2024-06-08 03:58:56.180 - bus - neon_messagebus.service:run:117 - INFO - Message bus service started!

**  end of bus log 
SESSION: {'active_skills': [['skill-fallback_unknown.neongeckocom', 1717848126.5338748]], 'utterance_states': {'skill-meal-plan.mikejgray': 'intent'}, 'session_id': 'default', 'lang': 'en-us', 'context': {'timeout': 120, 'frame_stack': []}, 'site_id': 'unknown', 'pipeline': ['stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'padatious_medium', 'adapt_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low'], 'location': {'city': {'code': 'Greenville', 'name': 'Greenville', 'state': {'code': 'SC', 'name': 'South Carolina', 'country': {'code': 'US', 'name': 'United States'}}}, 'coordinate': {'latitude': 34.8308, 'longitude': -82.3507}, 'timezone': {'code': 'America/New_York', 'name': 'America/New_York', 'dstOffset': 3600000, 'offset': -28800000}}, 'system_unit': 'imperial', 'time_format': 'half', 'date_format': 'MDY', 'is_speaking': False, 'is_recording': False, 'blacklisted_skills': ['skill-ovos-setup.openvoiceos', 'skill-messaging.neongeckocom', 'skill-custom_conversation.neongeckocom', 'skill-instructions.neongeckocom', 'skill-audio_record.neongeckocom'], 'blacklisted_intents': []}
2024-06-08 05:12:20.433 - bus - ovos_messagebus.event_handler:on_message:51 - DEBUG - skill-date_time.neongeckocom.get_month_date source: [] destination: []
SESSION: {'active_skills': [['skill-fallback_unknown.neongeckocom', 1717848126.5338748]], 'utterance_states': {'skill-meal-plan.mikejgray': 'intent'}, 'session_id': 'default', 'lang': 'en-us', 'context': {'timeout': 120, 'frame_stack': []}, 'site_id': 'unknown', 'pipeline': ['stop_high', 'converse', 'padatious_high', 'adapt_high', 'fallback_high', 'stop_medium', 'padatious_medium', 'adapt_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low'], 'location': {'city': {'code': 'Greenville', 'name': 'Greenville', 'state': {'code': 'SC', 'name': 'South Carolina', 'country': {'code': 'US', 'name': 'United States'}}}, 'coordinate': {'latitude': 34.8308, 'longitude': -82.3507}, 'timezone': {'code': 'America/New_York', 'name': 'America/New_York', 'dstOffset': 3600000, 'offset': -28800000}}, 'system_unit': 'imperial', 'time_format': 'half', 'date_format': 'MDY', 'is_speaking': False, 'is_recording': False, 'blacklisted_skills': ['skill-ovos-setup.openvoiceos', 'skill-messaging.neongeckocom', 'skill-custom_conversation.neongeckocom', 'skill-instructions.neongeckocom', 'skill-audio_record.neongeckocom'], 'blacklisted_intents': []}
2024-06-08 05:12:20.481 - bus - ovos_messagebus.event_handler:on_message:51 - DEBUG - skill-date_time.neongeckocom.get_month_date.response source: [] destination: []
SESSION: {'active_skills': [['skill-fallback_unknown.neongeckocom', 1717848126.5338748]], 'utterance_states': {'skill-meal-
![10Mb_of_files](https://github.com/NeonGeckoCom/NeonCore/assets/25271367/23687437-b36a-4637-81f1-baeeeee5ac17)
plan.mikejgray': 'intent'}, 'session_id': 'default', 'lang': 'en-us', 'context': {'timeout': 120, 'frame_stack': []}, 'site_id': 'unkn
```
![10Mb_of_files](https://github.com/NeonGeckoCom/NeonCore/assets/25271367/24ad0891-c3ae-43f6-9f36-45ea3ed0826b)
![no_updates](https://github.com/NeonGeckoCom/NeonCore/assets/25271367/252ce013-c3d0-4ae2-8694-44e4e4501009)

[date.time-logging.tar.gz](https://github.com/user-attachments/files/15752735/date.time-logging.tar.gz)

**Comment by NeonDaniel** [comment] 2024-06-11 20:45
Duplicate of https://github.com/NeonGeckoCom/neon_debos/issues/145

**Closed by NeonDaniel** 2024-06-11 20:45 UTC
Labels: bug, triage
